language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t johncaustin/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true johncaustin/docker-react npm run test